SELECT C.FIRSTNAME, C.LASTNAME, O.ORDERDATE, O.ORDERNUMBER, OI.QUANTITY * OI.UNITPRICE AS TOTAL, P.PRODUCTNAME, S.COMPANYNAME 
FROM CUSTOMERS_JIBE2 C
INNER JOIN ORDERS_JIBE2 O ON C.ID = O.CUSTOMERID
INNER JOIN ORDERITEMS_JIBE2 OI ON OI.ORDERID = O.ID
INNER JOIN PRODUCTS_JIBE2 P ON P.ID = OI.PRODUCTID
INNER JOIN SUPPLIERS_JIBE2 S ON S.ID = P.SUPPLIERID
WHERE C.ID = 1

SELECT distinct(S.COMPANYName)
FROM CUSTOMERS_JIBE2 C
INNER JOIN ORDERS_JIBE2 O ON C.ID = O.CUSTOMERID
INNER JOIN ORDERITEMS_JIBE2 OI ON OI.ORDERID = O.ID
INNER JOIN PRODUCTS_JIBE2 P ON P.ID = OI.PRODUCTID
INNER JOIN SUPPLIERS_JIBE2 S ON S.ID = P.SUPPLIERID
WHERE s.COUNTRY = 'USA'
AND C.COUNTRY = 'GERMANY';

--NOT BROUGHT ANYTING
SELECT distinct(c.firstName)
FROM CUSTOMERS_JIBE2 C
LEFT JOIN ORDERS_JIBE2 O ON C.ID = O.CUSTOMERID
WHERE O.ID IS NULL

CREATE INDEX IDX_ORDERID ON ORDERITEMS_JIBE2(ORDERID ASC)

select * from employee_jibe

select e.name as employee_name, m.name as manager_name
from employee_jibe e inner join employee_jibe m
on e.mgr_id = m.emp_id;



SELECT
	STRING_AGG(e.name,',') AS EMPLOYEE_JIBEs,
	m.name as manager_name
From EMPLOYEE_JIBE e
INNER JOIN EMPLOYEE_JIBE m
	ON e.mgr_id = m.emp_id
GROUP BY m.name;

SELECT
	STRING_AGG(e.name,',') AS EMPLOYEE_JIBEs,
	m.name as manager_name
From EMPLOYEE_JIBE e
INNER JOIN EMPLOYEE_JIBE m
	ON e.mgr_id = m.emp_id
GROUP BY m.name;

SELECT
	M.NAME AS MANAGER_NAME
	FROM EMPLOYEE_JIBE E
RIGHT JOIN EMPLOYEE_JIBE M
	ON E.MGR_ID = M.EMP_ID
WHERE E.NAME IS NULL

