SELECT * FROM EMPLOYEE_JIBE 
SELECT * FROM CUSTOMERS_JIBE

SELECT NAME, LASTNAME FROM EMPLOYEE_JIBE 
INTERSECT
SELECT FIRSTNAME, LASTNAME FROM CUSTOMERS_JIBE

SELECT NAME, LASTNAME FROM EMPLOYEE_JIBE 
UNION 
SELECT FIRSTNAME, LASTNAME FROM CUSTOMERS_JIBE

SELECT NAME, LASTNAME FROM EMPLOYEE_JIBE 
UNION ALL
SELECT FIRSTNAME, LASTNAME FROM CUSTOMERS_JIBE

SELECT NAME, LASTNAME FROM EMPLOYEE_JIBE 
EXCEPT
SELECT FIRSTNAME, LASTNAME FROM CUSTOMERS_JIBE

SELECT STANDARD, COUNT(*) FROM STUDENTS_JIBE
GROUP BY STANDARD
ORDER BY STANDARD

WITH CTE AS 
(
	SELECT CAST(STANDARD AS VARCHAR(2)) AS STANDARD, COUNT(*) AS CT FROM STUDENTS_JIBE
	GROUP BY STANDARD
)
SELECT STANDARD, CT FROM CTE
UNION
SELECT 'HIGHEST', MAX(CT) FROM CTE
UNION
SELECT 'LOWEST', MIN(CT) FROM CTE
UNION
SELECT 'AVERAGE', AVG(CT) FROM CTE

SELECT CAST(STANDARD AS VARCHAR(2)) AS STANDARD, COUNT(*) AS CT FROM STUDENT_JIBE
GROUP BY STANDARD
UNION
SELECT 'HIGHEST',
(
	SELECT MAX(CT) FROM 
	(
		SELECT COUNT(*) AS CT FROM STUDENT_JIBE
		GROUP BY STANDARD
	) AS T
)

CREATE VIEW PROTECTED_STUDENTS AS 
SELECT ROLL, SNAME, ENGLISH, MATHS, SCIENCE, STANDARD, DIVISION
FROM STUDENTS_JIBE

SELECT * FROM PROTECTED_STUDENTS

SELECT 
	t.name as table_name
	s.name as schema_name
from sys.tables t 
join sys.schemas s 
	on t.schema

select * from common_data





